baseURL = 'https://jiangdianhaode.github.io/newsite/'
languageCode = 'en-us'
publishDir = "docs"
canonifyurls = true
title = '首页'
theme = 'ananke'


[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

