baseURL = 'https://example.org/'
languageCode = 'en-us'
publishDir = "docs"
title = '首页'
theme = 'ananke'
canonifyurls = true

[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

